apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: apiworld-demo
build:
  artifacts:
  - image: quay.io/chak/react-ui
    context: react-ui 
  - image: quay.io/chak/golang-api
    context: golang    
    docker:
        dockerfile: Dockerfile.dev
  - image: quay.io/chak/nodejs-api
    context: nodejs
    docker:
        dockerfile: Dockerfile.dev
deploy:
  kubectl:
    manifests:
    - react-ui/deploy/*
    - nodejs/deploy/*
    - golang/deploy/*
    - common/deploy/*
