apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: apiworld-demo
build:
  artifacts:
  - image: quay.io/chak/react-ui
    context: react-ui 
  - image: quay.io/chak/golang-api
    context: golang    
    docker:
        dockerfile: Dockerfile.dev
    sync:
      infer:
      - 'bin/golang-api'
  - image: quay.io/chak/nodejs-api
    context: nodejs
    docker:
        dockerfile: Dockerfile.dev
    sync:
      manual:
      - src: './**/*.js'
        dest: '/app/'  
deploy:
  kubectl:
    manifests:
    - react-ui/deploy/*
    - nodejs/deploy/*
    - golang/deploy/*
    - common/deploy/*
