apiVersion: v1
kind: Service
metadata:
  labels:
    app: golang-api
  name: golang-api
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: golang-api
  type: ClusterIP
status:
  loadBalancer: {}
