virtualCluster:
  image: rancher/k3s:v1.18.6-k3s1
  extraArgs:
    - --service-cidr=10.43.0.0/16 # THE CLUSTER SERVICE CIDR HERE
storage:
  size: 5Gi

syncer:
 #extraArgs: ["--disable-sync-resources=ingresses"]
 image: loftsh/virtual-cluster